version: '3.8'

services:
  contabo-bot:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./bot.py:/app/bot.py
      - ./billing.py:/app/billing.py
      - ./requirements.txt:/app/requirements.txt
    env_file:
      - ./.env
    command: bash -c "pip install --no-cache-dir -r requirements.txt && python bot.py  "
